apiVersion: v1
kind: Secret
metadata:
  name: tasky-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://wizadmin:wizpassword123@10.0.1.88:27017/go-mongodb?authSource=admin"
  SECRET_KEY: "supersecret123"