name: App Build and Security

on:
  push:
    branches: [main]
  pull_request:

jobs:
  app-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --redact --verbose --exit-code=0

      - name: Build Docker image
        run: docker build -t tasky-app ./app

      - name: Run Trivy scan
        run: docker run --rm aquasec/trivy image tasky-app