name: CI-Security-Pipeline

on:
  push:
    branches: [main]

jobs:
  security:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Run Checkov (IaC security)
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform

    - name: Run Gitleaks (secrets scanning)
      uses: gitleaks/gitleaks-action@v2

    - name: Build Docker image
      run: docker build -t wiz-app ./app

    - name: Run Trivy scan (container security)
      run: |
        docker run --rm aquasec/trivy image wiz-app