name: CI-Security-Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          skip_check: CKV_TF_1

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Build Docker image
        run: docker build -t wiz-app ./app

      - name: Run Trivy scan
        run: docker run --rm aquasec/trivy image wiz-app
