name: Terraform Security

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          skip_check: CKV_TF_1